version: '3'
services:
  nos:
    build:
      dockerfile: Dockerfile
      context: ./php-cli
    volumes:
     - ./noslite:/var/www/noslite
    command: crond -f
    depends_on:
      - initialize
  nginx:
    ports:
      - 1234:80
    volumes:
     - ./noslite:/var/www/noslite
    build:
      dockerfile: Dockerfile
      context: ./nginx
  composer:
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    build:
      dockerfile: Dockerfile
      context: ./composer
    volumes:
     - ./noslite:/var/www/noslite
  initialize:
    build:
      dockerfile: Dockerfile
      context: ./php-cli
    volumes:
     - ./noslite:/var/www/noslite
    command: php src/noslite.php

